### ISSUE TITLE
installation issue 

### ISSUE THREAD

**Issue by Sijaz1** [Functional-Genomics/CrossSpeciesIntegration#4]
Hi I am trying to install it but it showing error like that:
 git clone -b main git@github.com:Functional-Genomics/BENGAL.git

Cloning into 'BENGAL'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

please let me know 
Thanks

**Comment by YY-SONG0718** [comment]
Hello,

Thanks for reaching out! I think this is an issue related to the GitHub SSH authentication on your machine rather than BENGAL issue. Could you please reset the authentication according to [this guide](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account)?

Kind regards,
Yuyao
